# Generated by Django 3.2 on 2021-12-16 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20211216_2011'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Awards',
            new_name='Award',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='company',
            new_name='companies',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='developer',
            new_name='developers',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='genre',
            new_name='genres',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='license',
            new_name='licenses',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='publisher',
            new_name='publishers',
        ),
    ]
